#!/bin/csh -f
# Installs mdexport and mdimport

# get the version number for python2
set vers=`python -c 'import sys; print("%s.%s" % (sys.version_info.major, sys.version_info.minor))'`
echo "Installing fvi to ~/.home/bin (Python$vers)."

# remove build directories from a previous install to assure a clean install
set nonomatch
rm -rf build dist *.egg-info install.out

# install pw
python$vers setup.py install --quiet --user >& install.out
if ($status) then
    echo "Problems found, aborting (see install.out)"
    exit(1)
endif

# remove build directories, because I like a clean directory
rm -rf build dist *.egg-info
